services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel_okru
    network_mode: "host"
    command: tunnel --no-autoupdate --url http://localhost:9622/
    restart: unless-stopped
